name: Deploy Server, Migrate Database, and Deploy Web
run-name: Deploying to ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || github.ref_name == 'main' && 'production' || github.ref_name == 'staging' && 'staging' || 'preview' }} Environment by ${{ github.actor }}

on:
  workflow_run:
    workflows: ["pr-merge-check"]
    types: [completed]
    branches: [main, staging]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "preview"
        type: choice
        options: ["production", "staging", "preview"]

env:
  WORKFLOW_DEPLOY_ENV: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || github.ref_name == 'main' && 'production' || github.ref_name == 'staging' && 'staging' || 'preview' }}

jobs:
  deploy:
    if: ${{ (github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success') && !startsWith(github.ref_name, 'release/') }}
    runs-on: ubuntu-latest
    timeout-minutes: 60

    # Determine environment based on branch or input
    environment:
      name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || github.ref_name == 'main' && 'production' || github.ref_name == 'staging' && 'staging' || 'preview' }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: cd packages/db && bun run check

      - name: Download deployment info
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/download-artifact@v4
        with:
          name: deployment-info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Set deployment variables from workflow run
        if: ${{ github.event_name == 'workflow_run' }}
        run: |
          DEPLOYMENT_NAME=$(cat deployment_name.txt)
          echo "DEPLOY_COMMAND=deploy --env $WORKFLOW_DEPLOY_ENV --name $DEPLOYMENT_NAME" >> $GITHUB_ENV

      - name: Set deployment variables from other events
        if: ${{ github.event_name != 'workflow_run' }}
        run: echo "DEPLOY_COMMAND=deploy --env ${{ env.WORKFLOW_DEPLOY_ENV }}" >> $GITHUB_ENV

      - name: Deploy Server Worker
        id: deploy-server-worker

        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
          MICROSOFT_CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          WEB_PORT: ${{ secrets.WEB_PORT }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          TRUSTED_ORIGINS: ${{ secrets.TRUSTED_ORIGINS }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          IS_EDGE_RUNTIME: ${{ secrets.IS_EDGE_RUNTIME }}

        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

          packageManager: bun
          workingDirectory: "apps/server"

          command: ${{ env.DEPLOY_COMMAND }}
          # This is required for wrangler to know which environment to deploy to even though --env ${{ env.WORKFLOW_DEPLOY_ENV }} is specified in the command
          environment: ${{ env.WORKFLOW_DEPLOY_ENV }}

          secrets: |
            GOOGLE_CLIENT_ID
            GOOGLE_CLIENT_SECRET
            MICROSOFT_CLIENT_ID
            MICROSOFT_CLIENT_SECRET
            BETTER_AUTH_SECRET
            BETTER_AUTH_URL
            SERVER_PORT
            WEB_PORT
            BACKEND_URL
            TRUSTED_ORIGINS
            DATABASE_URL
            DATABASE_HOST
            POSTGRES_PORT
            POSTGRES_USER
            POSTGRES_PASSWORD
            POSTGRES_DB
            UPSTASH_REDIS_REST_URL
            UPSTASH_REDIS_REST_TOKEN
            EMAIL_FROM
            RESEND_API_KEY
            IS_EDGE_RUNTIME

      - name: Print Server deployment URL
        env:
          SERVER_DEPLOYMENT_URL: ${{ steps.deploy-server-worker.outputs.deployment-url }}
        run: echo $SERVER_DEPLOYMENT_URL

      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: cd packages/db && bun run migrate

      - name: Deploy Web Worker
        id: deploy-web-worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          NEXT_PUBLIC_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
          NEXT_PUBLIC_FRONTEND_URL: ${{ secrets.NEXT_PUBLIC_FRONTEND_URL }}
        run: cd apps/web && bun run cf:build && bun run cf:deploy:${{ env.WORKFLOW_DEPLOY_ENV }}

      - name: Print Web deployment URL
        env:
          WEB_DEPLOYMENT_URL: ${{ steps.deploy-web-worker.outputs.deployment-url }}
        run: echo $WEB_DEPLOYMENT_URL

      - name: Create Release
        if: ${{ github.ref_name == 'main' && env.WORKFLOW_DEPLOY_ENV == 'production' }}
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/release.sh
