name: Deploy Server (Staging)
on:
  pull_request:
    branches:
      - staging
  workflow_dispatch:

env:
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
  MICROSOFT_CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
  BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
  BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
  WEB_PORT: ${{ secrets.WEB_PORT }}
  BACKEND_URL: ${{ secrets.BACKEND_URL }}
  TRUSTED_ORIGINS: ${{ secrets.TRUSTED_ORIGINS }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
  UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
  EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
  IS_EDGE_RUNTIME: ${{ secrets.IS_EDGE_RUNTIME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Deploy Worker
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: bun
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "apps/server"
          command: deploy --env staging
          secrets: |
            GOOGLE_CLIENT_ID
            GOOGLE_CLIENT_SECRET
            MICROSOFT_CLIENT_ID
            MICROSOFT_CLIENT_SECRET
            BETTER_AUTH_SECRET
            BETTER_AUTH_URL
            SERVER_PORT
            WEB_PORT
            BACKEND_URL
            TRUSTED_ORIGINS
            DATABASE_URL
            DATABASE_HOST
            POSTGRES_PORT
            POSTGRES_USER
            POSTGRES_PASSWORD
            POSTGRES_DB
            UPSTASH_REDIS_REST_URL
            UPSTASH_REDIS_REST_TOKEN
            EMAIL_FROM
            RESEND_API_KEY
            IS_EDGE_RUNTIME

      - name: print deployment-url
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        run: echo $DEPLOYMENT_URL
